baseurl = "/"
title = "Yankos Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Welcome to yankos.co.uk"
    description = "Project step by step Walkthroughs"
    github = "https://github.com/IoannisGianko"
    twitter = "https://twitter.com/Anri888"
	LinkedIn = "https://www.linkedin.com/in/ioannis-gianko-36b1a2a3/"
    email = "ioannis@yankos.co.uk"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"